### PR TITLE
Search tests and bug fixes

### LINKED ISSUE #27: Add Pagination for elastic search requests

### LINKED ISSUE #54: Search Test Coverage

### PR DESCRIPTION
**Pull request by EquilibriaW**
closes #54
closes #27

### CODE REVIEW

**Comment by alexrosen45** [comment]
name your PRs

**Comment by alexrosen45** [comment]
This PR addresses search testing but you called it settings test

File: src/entities/settings/SettingsChangeResponse.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
+package entities.settings;
+
+public class SettingsChangeResponse {
+  private final String error;
+  private final Boolean isError;
+
+  public SettingsChangeResponse(String error, Boolean isError) {
```
Comment (alexrosen45) [inline src/entities/settings/SettingsChangeResponse.java:7]: This should only take a String error, and `isError` should return `error != null`. At least get rid of this `getIsError` stuff

File: src/interface_adapter/login/LoginPresenter.java [hunk 2]
```diff
@@ -32,6 +32,7 @@ public LoginPresenter(
   public void prepareSuccessView(LoginOutputData response) {
     LoggedInState loggedInState = loggedInViewModel.getState();
     loggedInState.setUsername(response.getUsername());
+    loggedInState.setUser(response.getUser());
```
Comment (alexrosen45) [inline src/interface_adapter/login/LoginPresenter.java:35]: Why do we need to set a user and set a username??

File: src/interface_adapter/settings/SettingsController.java [hunk 3]
```diff
@@ -12,8 +12,8 @@ public SettingsController(SettingsInputBoundary settingsUseCaseInteractor) {
     this.settingsUseCaseInteractor = settingsUseCaseInteractor;
   }
 
-  public void execute(AbstractUser user) {
-    SettingsInputData settingsInputData = new SettingsInputData(user);
-    settingsUseCaseInteractor.execute(settingsInputData);
+  public void executeChangeUsername(String username, User user) {
```
Comment (alexrosen45) [inline src/interface_adapter/settings/SettingsController.java:15]: Just call this `changeUsername` and not execute change username

File: src/interface_adapter/settings/SettingsPresenter.java [hunk 4]
```diff
@@ -12,14 +12,16 @@ public SettingsPresenter(SettingsViewModel settingsViewModel) {
   }
 
   @Override
-  public void prepareSuccessView(SettingsOutputData response) {
+  public void prepareSuccessView(SettingsOutputData outputData) {
     // On success, switch back to the same view for now
     System.out.println("success");
```
Comment (alexrosen45) [inline src/interface_adapter/settings/SettingsPresenter.java:17]: get rid of this

File: src/interface_adapter/settings/StartSettingsController.java [hunk 5]
```diff
@@ -0,0 +1,18 @@
+package interface_adapter.settings;
+
+import entities.auth.User;
+
+public class StartSettingsController {
+  // This controller follows the MVC architecture, as it needs to only change external files
```
Comment (alexrosen45) [inline src/interface_adapter/settings/StartSettingsController.java:6]: strike again!?

File: src/use_case/settings/SettingsInteractor.java [hunk 6]
```diff
@@ -1,25 +1,34 @@
 package use_case.settings;
 
-import entities.auth.AbstractUser;
-
 public class SettingsInteractor implements SettingsInputBoundary {
   // TODO: Add this after other code is merged
```
Comment (alexrosen45) [inline src/use_case/settings/SettingsInteractor.java:4]: What's this comment? Still relevant?

File: src/use_case/settings/SettingsInteractor.java [hunk 7]
```diff
@@ -1,25 +1,34 @@
...
-    // TODO: Write interaction after other code is merged
-    SettingsOutputData settingsOutputData = new SettingsOutputData(user, true);
-    settingsPresenter.prepareSuccessView(settingsOutputData);
+  public void executeChangeUsername(SettingsInputData settingsInputData) {
+    try {
+      userSettingsDataAccessObject.changeDisplayName(
+          settingsInputData.getUser(), settingsInputData.getUpdatedUsername());
+      roomsSettingsDataAccessObject.propogateDisplayNameChange(
+          settingsInputData.getUser(), settingsInputData.getUpdatedUsername());
+      SettingsOutputData settingsOutputData = new SettingsOutputData(null, false);
```
Comment (alexrosen45) [inline src/use_case/settings/SettingsInteractor.java:27]: New username should be passed here to update the view instead of having to login and logout again.

File: src/view/SearchView.java [hunk 8]
```diff
@@ -58,6 +58,18 @@ protected void update() {
         });
   }
 
+  public JButton getSearchButton() {
```
Comment (alexrosen45) [inline src/view/SearchView.java:61]: Leave a comment saying that these methods are for testing purposes.

File: tests/SearchTest.java [hunk 9]
```diff
@@ -1,29 +1,144 @@
...
+
+  SearchViewModel searchViewModel;
+
+  SearchedViewModel searchedViewModel;
+  ViewManagerModel viewManagerModel;
+  SwitchViewController switchViewController;
+  JPanel views;
+
+  @Before
+  public void setUp() {
```
Comment (alexrosen45) [inline tests/SearchTest.java:33]: Just test the regular view... why build a new one? Limits line coverage for tests and doesn't seem necessary

File: tests/SearchTest.java [hunk 10]
```diff
@@ -1,29 +1,144 @@
...
-    SearchRequest searchRequest = new SearchRequest("dog", "2");
+    SearchRequest searchRequest = new SearchRequest("Test message!", "dummyRoomUid");
     assertEquals(
         searchDataAccessObject.getData(searchRequest).getResponses().get(0).getFullText(),
-        "I love dogs");
+        "Test message!");
+  }
+
+  @Test
+  public void testGetNoData() {
```
Comment (alexrosen45) [inline tests/SearchTest.java:61]: rename

File: tests/SearchTest.java [hunk 11]
```diff
@@ -1,29 +1,144 @@
...
+    SearchRequest searchRequest = new SearchRequest("a", "Bro");
+    assertEquals(
+        searchDataAccessObject.getData(searchRequest).getError(), "No search results found.");
+  }
+
+  @Test
+  public void testSave() {
```
Comment (alexrosen45) [inline tests/SearchTest.java:68]: rename

File: tests/SearchTest.java [hunk 12]
```diff
@@ -1,29 +1,144 @@
...
+    JFrame jf = new JFrame();
+    jf.setContentPane(searchview.contentPane);
+    jf.pack();
+    jf.setVisible(true);
+    searchview.getBackButton().doClick();
+    assertEquals("logged in", viewManagerModel.getActiveView());
+  }
+
+  @Test
+  public void testSearchViewSearch() {
```
Comment (alexrosen45) [inline tests/SearchTest.java:91]: clever name!

File: tests/SearchTest.java [hunk 13]
```diff
@@ -1,29 +1,144 @@
...
+    jf.pack();
+    jf.setVisible(true);
+    searchController.executeSearchRequest("dummyRoomUid", "Test message!", "abc");
+    assertEquals("search results", viewManagerModel.getActiveView());
+    searchedview.getBackButton().doClick();
+    assertEquals("search", viewManagerModel.getActiveView());
+  }
+
+  @Test
+  public void testError() {
```
Comment (alexrosen45) [inline tests/SearchTest.java:131]: rename

**Comment by alexrosen45** [comment]
This PR has a ton of conflicts. Would be faster to copy all your tests, pull the changes from main, then make a new PR with them.

**Comment by uoftm** [comment]
any form of fixing conflicts here will likely purge the review, but @EquilibriaW there is a fixed branch at alexw/2023-12-06/search-test (maybe you could force push that HEAD to alexw/06/settings-test to preserve the PR?)

**Comment by alexrosen45** [comment]
> > This PR has a ton of conflicts. Would be faster to copy all your tests, pull the changes from main, then make a new PR with them.
> 
> Ok, I resolved the conflicts.

Taking a look now

**Comment by alexrosen45** [comment]
Please test and run your code before asking for a review. The program doesn't compile:
```
package use_case.settings;

public class SettingsOutputData {
  private String error;

  public SettingsOutputData(String error) {
    this.error = error;
  }

  public boolean getIsError() {
    return isError;
  }

  public String getError() {
    return error;
  }
}
```
You need to change `isError` to `error != null`

**Review by alexrosen45 — DISMISSED** [review]
Search is finally working and there are comprehensive tests. Great job!!

**Comment by alexrosen45** [comment]
> [@EquilibriaW](/EquilibriaW) [EquilibriaW](/EquilibriaW) dismissed [alexrosen45](/alexrosen45)’s [stale review](#pullrequestreview-1768877920) [ December 6, 2023 19:14 ](#event-11174979050)
> The merge-base changed after approval.

?

**Review by alexrosen45 — APPROVED** [review]

File: src/use_case/settings/SettingsOutputData.java [hunk 14]
```diff
@@ -1,18 +1,14 @@
...
 public class SettingsOutputData {
+  private String error;
 
-  AbstractUser user;
-  private final boolean useCaseFailed;
-
-  public SettingsOutputData(AbstractUser user, boolean useCaseFailed) {
-    this.user = user;
-    this.useCaseFailed = useCaseFailed;
+  public SettingsOutputData(String error) {
```
Comment (alexrosen45) [inline src/use_case/settings/SettingsOutputData.java:6]: good

**Review by alexrosen45 — APPROVED** [review]

File: tests/view/SearchTest.java [hunk 15]
```diff
@@ -87,6 +56,14 @@ public void testSearchViewBack() {
     assertEquals("logged in", viewManagerModel.getActiveView());
   }
 
+  @Test
+  public void testSavaDataFromController() {
```
Comment (alexrosen45) [inline tests/view/SearchTest.java:60]: good, nice job

**Review by alexrosen45 — DISMISSED** [review]
